### ISSUE TITLE
1.0.0 release does not have helm chart attached :)

### ISSUE THREAD

**Issue by skurfuerst** [ml-tooling/ml-hub#6]
Hey,

as written in the README, the release should have the helm chart attached - but I did not find this so far.

I'd be glad for a quick pointer where the helm chart could be.

All the best :) 
Sebastian

**Comment by raethlein** [comment]
Hey Sebastian, 

thanks for pointing out the missing chart. I just added it!

In case you want tomodify the source or just want to build it locally instead of having to wait, you can execute `python build.py --version a.b.c-SNAPSHOT` in the hub root folder and find the created chart in the `./helmchart` directory. It is just locally built and not pushed anywhere. If you just want to create the chart, 
you have to modify the $VERSION placeholders in `./helmchart/mlhub/Chart.yaml` and `./helmchart/mlhub/values.yaml` manually and then execute `helm package ./helmchart/mlhub -d helmchart`.

Please let me know if the chart works or whether this comment helps so that I can close the issue 🙂 

Kind regards,
Ben

**Comment by skurfuerst** [comment]
Yep all works :) I was able to build it beforehand in exactly this way 👍👍👍

Thanks again for your awesome work and keep it up. This project deserves way more attention publicly :)

**Comment by raethlein** [comment]
Thanks a lot, we really appreciate your kind feedback and contribution 🙂
